<?php
$headTitle = 'Ajax';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-sm-12">
        <h3><?= $this->escapeHtml($headTitle) ?></h3>
    </div>
</div>
<div><?= $this->escapeHtml($this->greetingService) ?></div>
<hr>
<?= date('H:i:s') ?>
<br>
<br>
<form id="ajax_form">
    <div class="row">
        <div class="col-lg-6 col-md-8 col-10">
            <div class="form-group row">
                <label class="control-label col-sm-3" for="firstName">First name:</label>
                <input type="text" name="firstName" class="form-control col-sm-9" id="firstName">
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-6 col-md-8 col-10">
            <div class="form-group row">
                <label class="control-label col-sm-3" for="lastName">Last name:</label>
                <input type="text" name="lastName" class="form-control col-sm-9" id="lastName">
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-6 col-md-8 col-10">
            <div class="row">
                <div class="offset-sm-3">
                    <button type="submit" class="btn btn-info ">Submit</button>
                </div>
            </div>
        </div>
    </div>
</form>
<br>
<p><strong id="result"></strong></p>
