<!-- In order to do top navigation link active -->
<?= $this->headScript()->prependScript('$(function(){$("ul.navbar-nav.mr-auto li").eq(0).addClass("active");});'); ?>
<?php
$headTitle = 'Example';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-sm-12">
        <h3><?= $this->escapeHtml($headTitle) ?></h3>
    </div>
</div>
<?= $this->partial('partial/flashMessage') ?>
<form action="/tutorial/example" method="post" class="form-inline">
    <div class="form-group">
        <input type="text" name="title" class="form-control">
    </div>
    <input type="submit" value="Submit" class="btn btn-info">
</form>
<br>
<div><?= $this->escapehtml($this->message); ?></div>
<br>
<div><a href="/tutorial/example/download" class="btn btn-info">Download</a></div>
<hr>
<div><a href="/tutorial/example/sample" class="btn btn-dark">Sample</a></div>
