<!-- In order to do top navigation link active -->
<?= $this->headScript()->prependScript('$(function(){$("ul.navbar-nav.mr-auto li").eq(0).addClass("active");});'); ?>

<?php

/*$stringLength = new \Zend\Validator\StringLength(['min' => 3, 'max' => 10]);
$stringLength->setMessages([
    \Zend\Validator\StringLength::TOO_SHORT => 'Too short',
    \Zend\Validator\StringLength::TOO_LONG  => 'Too long',
]);

$notEmpty = new \Zend\Validator\NotEmpty();
$notEmpty->setMessage('The value is empty', \Zend\Validator\NotEmpty::IS_EMPTY);

$validatorChain = new \Zend\Validator\ValidatorChain();
$validatorChain->attach($stringLength);
$validatorChain->attach($notEmpty);*/

/*$validatorChain = new \Zend\Validator\ValidatorChain();
$validatorChain->attachByName('StringLength', ['min' => 3, 'max' => 10]);

$str = '';
if ($validatorChain->isValid($str)) {
    echo 'Ok';
} else {
    foreach ($validatorChain->getMessages() as $message) {
        echo '<div>' . $message . '</div>';
    }
}*/

/*$floatValidator = new \Tutorial\Validator\FloatValidator();

$val = 10.2;
if ($floatValidator->isValid($val)) {
    echo 'Ok';
} else {
    foreach ($floatValidator->getMessages() as $message) {
        echo '<div>' . $message . '</div>';
    }
}

echo '<hr>';*/
?>

<?php

/*$htmlEntities = new \Zend\Filter\HtmlEntities();
$stringTrim   = new \Zend\Filter\StringTrim();

$filterChain = new \Zend\Filter\FilterChain();
$filterChain->attach($htmlEntities);
$filterChain->attach($stringTrim);*/



$filterChain = new \Zend\Filter\FilterChain();
$filterChain->attachByName('HtmlEntities');
$filterChain->attachByName('StringTrim');

$str = '<a href="#">link</a>';
//$str = '                   Hello world!';

$filteredStr = $filterChain->filter($str);
echo $filteredStr;

echo '<hr>';
?>




<?php
$headTitle = 'Sample';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-sm-12">
        <h3><?= $this->escapeHtml($headTitle) ?></h3>
    </div>
</div>
<?= $this->escapeHtml($this->url()) ?>
<hr>
<div><?= $this->data ?></div>
<div><?= $this->num ?></div>
<div><?= $this->widget ?></div>
<div><a href="/tutorial/example" class="btn btn-dark">Back to example</a></div>
