<!-- In order to do top navigation link active -->
<?= $this->headScript()->prependScript('$(function(){$("ul.navbar-nav.mr-auto li").eq(0).addClass("active");});'); ?>
<?php
$headTitle = 'Edit article';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-sm-12">
        <h3><?= $this->escapeHtml($headTitle) ?></h3>
    </div>
</div>
<div>
    <form action="/tutorial/article/edit/14" method="post" class="form-inline">
        <input type="text" name="title" class="form-control">
        <input type="submit" name="add_form" value="Submit" class="btn btn-info">
    </form>
</div>
