<?php
$headTitle = $this->escapeHtml($article->getTitle());
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-sm-6">
        <h4><?= $this->escapeHtml($headTitle) ?></h4>
    </div>
    <div class="col-sm-6">
        <div class="breadcrumb-box float-right">
            <?= $this->navigation('blog_breadcrumb')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb'); ?>
        </div>
    </div>
</div>
<br>
<br>
<div>
    <div class="panel panel-group">
        <div class="panel-heading">
            <img src="<?= $this->escapeHtml($this->checkImage($article->getImage())) ?>"
                 class="blog-image img-responsive float-left"
            >
        </div>
        <div class="clearfix"></div>
        <br>
        <div class="panel-body">
            <?= $this->escapeHtml($article->getContent()) ?>
        </div>
    </div>
    <hr>
</div>
<br>
<br>
