<?php
$headTitle = $this->escapeHtml($article->getTitle());
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-sm-12">
        <h4><?= $this->escapeHtml($headTitle) ?></h4>
    </div>
</div>
<br>
<br>
<div>
    <div class="panel panel-group">
        <div class="panel-heading">
            <img src="<?= $this->escapeHtml($this->checkImage($article->getImage())) ?>"
                 class="blog-image img-responsive float-left"
            >
        </div>
        <div class="clearfix"></div>
        <br>
        <div class="panel-body">
            <?= $this->escapeHtml($article->getContent()) ?>
        </div>
        <div class="panel-footer">
            <div class="text-right"><a href="<?= $this->url('blog') ?>" class="btn btn-sm btn-dark">Back</a></div>
        </div>
    </div>
    <hr>
</div>
<br>
<br>
