<?php
$headTitle = 'Blog';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-sm-6">
        <h4><?= $this->escapeHtml($headTitle) ?></h4>
    </div>
    <div class="col-sm-6">
        <div class="breadcrumb-box float-right">
            <?= $this->navigation('blog_breadcrumb')->breadcrumbs()->setMinDepth(0)->setPartial('partial/breadcrumb'); ?>
        </div>
    </div>
</div>
<br>
<br>
<div>
    <?php foreach ($this->articles as $article) : ?>

    <div class="panel panel-group">
        <div class="panel-heading">
            <img src="<?= $this->escapeHtml($this->checkImage($article->getImage())) ?>"
                 class="blog-image-thumbnail img-responsive float-left"
            >
            <h5 class="panel-title">
                <a href="<?= $this->url('blog', ['action' => 'article', 'id' => $article->getId()]) ?>">
                    <?= $this->escapeHtml($article->getTitle()) ?>
                </a>
            </h5>
        </div>
        <div class="clearfix"></div>
        <div class="panel-body">
            <?= $this->escapeHtml($article->getShortContent()) ?>
        </div>
        <div class="panel-footer">
            <div class="text-right">
                <a href="<?= $this->url('blog', ['action' => 'article', 'id' => $article->getId()]) ?>" class="btn btn-sm btn-dark">
                    Read more
                </a>
            </div>
        </div>
    </div>
    <hr>

    <?php endforeach; ?>
</div>
<br>
<br>
<?php
    echo $this->paginationControl(
        $this->articles,
        'sliding',
        'partial/paginator',
        ['route' => 'blog']
    );
?>
